import WhiteCheckers from '../image/white.png';
import BlackCheckers from '../image/black.png';

const boardMap = [
  ['Empty', ''],
  // [BlackCheckers, 'black, 24'],
  ['Empty', ''],
  // [BlackCheckers, 'black, 23'],
  ['Empty', ''],
  // [BlackCheckers, 'black, 22'],
  ['Empty', ''],
  // [BlackCheckers, 'black, 21'],
  // [BlackCheckers, 'black, 20'],
  ['Empty', ''],
  // [BlackCheckers, 'black, 19'],
  ['Empty', ''],
  // [BlackCheckers, 'black, 18'],
  ['Empty', ''],
  // [BlackCheckers, 'black, 17'],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  [BlackCheckers, 'black, 16'],
  ['Empty', ''],
  [BlackCheckers, 'black, 15'],
  ['Empty', ''],
  [BlackCheckers, 'black, 14'],
  ['Empty', ''],
  [BlackCheckers, 'black, 13'],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  [WhiteCheckers, 'white, 1'],
  ['Empty', ''],
  [WhiteCheckers, 'white, 2'],
  ['Empty', ''],
  [WhiteCheckers, 'white, 3'],
  ['Empty', ''],
  [WhiteCheckers, 'white, 4'],
  ['Empty', ''],
  ['Empty', ''],
  // [WhiteCheckers, 'white, 5'],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  // [WhiteCheckers, 'white, 6'],
  ['Empty', ''],
  // [WhiteCheckers, 'white, 7'],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  // [WhiteCheckers, 'white, 8'],
  // [WhiteCheckers, 'white, 9'],
  ['Empty', ''],
  // [WhiteCheckers, 'white, 10'],
  ['Empty', ''],
  // [WhiteCheckers, 'white, 11'],
  ['Empty', ''],
  // [WhiteCheckers, 'white, 12'],
  ['Empty', '']
];

export default boardMap;
