import WhiteCheckers from "../image/white.png";
import BlackCheckers from "../image/black.png";
import WhiteQueen from "../image/whiteQueen.png";
import blackQueen from "../image/BlackQueen.png";

const boardMap = [
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  [BlackCheckers, "white, 20"],

  // [WhiteQueen, "blackQueen,black"],
  // [WhiteQueen, "blackQueen,black"],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],

  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  // [WhiteCheckers, "black, 21"],
  ["Empty", ""],
  [BlackCheckers, "white, 20"],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  [WhiteCheckers, "white, 21"],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  [WhiteQueen, "blackQueen,black"],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
  ["Empty", ""],
];

export default boardMap;
