import WhiteCheckers from '../image/white.png';
import BlackCheckers from '../image/black.png';
import WhiteQueen from '../image/whiteQueen.png';
import blackQueen from '../image/BlackQueen.png';

const boardMap = [
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  [WhiteQueen, 'whiteQueen,white'],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  [WhiteQueen, 'whiteQueen,white'],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  [WhiteQueen, 'whiteQueen,white'],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', ''],
  ['Empty', '']
];

export default boardMap;
